name: Lock and Redirect Issues

on:
  issues:
    types: [opened]

jobs:
  lock-or-redirect:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Lock Maintainer Issue
        if: contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR", "CONTRIBUTOR"]'), github.event.issue.author_association)
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.lock({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
